name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Exec build
      run : |
        ./autogen.sh
        ./configure --without-mysql
        make -j
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sysbench
        path: src/sysbench
